---
version: '3.7'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders-service
      MYSQL_USER: root
      MYSQL_PASSWORD: root
volumes:
  mysql_data: